# Generated by Django 4.0.4 on 2022-06-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'baresi'), (2, 'darhal_baresi'), (3, 'baresi_nashode')], default=3)),
                ('phonnum', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ticketing.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='responseticket',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticketing.ticketing'),
        ),
        migrations.DeleteModel(
            name='Ticheting',
        ),
    ]
