# Generated by Django 4.0.4 on 2022-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_ticketing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'baresi'), (2, 'darhal_baresi'), (3, 'baresi_nashode')], default='baresi_nashode'),
        ),
    ]
