# Generated by Django 4.0.4 on 2022-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_ticketing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketing',
            name='type',
        ),
        migrations.AddField(
            model_name='ticketing',
            name='status',
            field=models.CharField(choices=[(1, 'baresi'), (2, 'darhal_baresi'), (3, 'baresi_nashode')], default=3, max_length=32),
        ),
    ]
