# Generated by Django 4.0.4 on 2022-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_remove_ticketing_type_ticketing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='status',
            field=models.CharField(choices=[(1, 'بررسی شده'), (2, 'درحال بررسی'), (3, 'بررسی نشده')], default=3, max_length=32),
        ),
    ]
