# Generated by Django 4.0.4 on 2022-07-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_remove_ticketing_phonnum_ticketing_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseticket',
            name='tickets',
        ),
        migrations.AddField(
            model_name='responseticket',
            name='ticket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticketing.ticketing'),
            preserve_default=False,
        ),
    ]
