# Generated by Django 4.0.4 on 2022-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_remove_responseticket_tickets_responseticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseticket',
            name='message',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
