# Generated by Django 4.0.4 on 2022-06-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=32),
        ),
    ]
