# Generated by Django 4.0.4 on 2022-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=32, null=True, verbose_name='Username'),
        ),
    ]
